version: '3.8'

services:
  catalog-db:
    image: postgres:latest
    container_name: catalog-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure-password
      POSTGRES_DB: "CatalogDb"
    ports:
      - "5432:5432"
    volumes:
      - catalogdata:/var/lib/postgresql/data
    profiles:
      - data
  basket-db:
    image: mongo:latest
    container_name: basket-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure-password
      MONGO_INITDB_DATABASE: basketDB
    ports:
      - "27017:27017"
    volumes:
      - basketdata:/data/db
    profiles:
      - data
  
  inventory-db:
    image: mongo:latest
    container_name: inventory-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure-password
      MONGO_INITDB_DATABASE: inventoryDB
    ports:
      - "27018:27017"
    volumes:
      - inventorydata:/data/db
    profiles:
      - data
  
  catalog-api:
    build:
      context: ./Catalog.API
      dockerfile: Dockerfile
    container_name: catalog-api
    environment:
      DB_HOST: catalog-db
      DB_NAME: CatalogDb
      DB_USER: admin
      DB_PASS: secure-password
    ports:
      - "8090:8080"
    depends_on:
      - catalog-db
    profiles:
      - apis



  basket-api:
    build:
      context: ./Basket.API
      dockerfile: Dockerfile
    container_name: basket-api
    
    environment:
      DB_HOST: basket-db
      DB_PORT: 27017
      DB_USER: admin
      DB_PASS: secure-password
      DB_NAME: basketDB
    ports:
      - "9090:8080"
    depends_on:
      - basket-db
    profiles:
      - apis
  
  inventory-api:
    build:
      context: ./Inventory.API
      dockerfile: Dockerfile
    container_name: inventory-api
    environment:
      DB_HOST: inventory-db
      DB_PORT: 27018
      DB_USER: admin
      DB_PASS: secure-password
      DB_NAME: inventoryDB
    ports:
      - "9091:8080"
    depends_on:
      - inventory-db
    profiles:
      - apis

volumes:
  catalogdata:
  basketdata:
  inventorydata:
